services:
  - type: web
    name: laravel-links
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /tmp/database.sqlite