services:
  - type: web
    name: laravel-links
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev
      php artisan config:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1